module.exports = {
  SEND_MESSAGE: 'EWM_SEND_MESSAGE', // 发送消息
  SEND_BROADCAST_MESSAGE: 'EWM_SEND_BROADCAST_MESSAGE', // 发送广播消息
  CREATE_WINDOW: 'EWM_CREATE_WINDOW', // 创建窗口
  GET_WINDOW_IDS: 'EWM_GET_WINDOW_IDS', // 获取窗口id
  UPDATE_MESSAGE: 'EWM_UPDATE_MESSAGE', // 更新消息(channel)
  UPDATE_WINDOW_IDS: 'EWM_UPDATE_WINDOW_IDS', // 更新窗口ids
  WINDOW_ACTION: 'EWM_WINDOW_ACTION', // 执行窗口动作
  GET_STATE: 'EWM_GET_STATE', // 获取共享状态
  SET_STATE: 'EWM_SET_STATE', // 设置共享状态
  UPDATE_STATE: 'EWM_UPDATE_STATE', // 更新共享状态
  STATE_UPDATED: 'EWM_STATE_UPDATED' // 共享状态已更新
}
